### ISSUE TITLE
Release on drupal.org

### ISSUE THREAD

**Issue by aurelianzaha** [payzen/plugin-drupalcommerce#1]
We plan to use the module EpayNC 7.x module in a project and would be glad to have a drupal.org release as well.
Is there a plan to do it?

**Comment by klausi** [comment]
The license says GPL and all Drupal modules are GPL automatically (derivative work of Drupal core which is GPL). From a licensing point of view it should not be a problem to put it on drupal.org.

We could also put it on drupal.org ourselves and add any maintainers here to be maintainers there if they want? Let's wait 2 weeks for a response here first :)

**Comment by nabil509** [comment]
Hi, 

Sorry for the delay.

We cannot release our white label plugins from drupal.org for now. This is not a priority for us for now.
